{"uid":"b4246fabad2a9c73","name":"test_registration_wrong_email[use r@teszt.hu]","fullName":"Sprint_1.POM.Registration.test_registration_negative_email.TestTC#test_registration_wrong_email","historyId":"44118d063374aecc2cf84ce22b762053","time":{"start":1750660239739,"stop":1750660239739,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x556a9026dc9a <unknown>\n#1 0x556a8fd136e0 <unknown>\n#2 0x556a8fd4e0b2 <unknown>\n#3 0x556a8fd4924f <unknown>\n#4 0x556a8fd998b6 <unknown>\n#5 0x556a8fd98f76 <unknown>\n#6 0x556a8fd8ac03 <unknown>\n#7 0x556a8fd5747b <unknown>\n#8 0x556a8fd580e1 <unknown>\n#9 0x556a9023244b <unknown>\n#10 0x556a9023637f <unknown>\n#11 0x556a90219f89 <unknown>\n#12 0x556a90236f18 <unknown>\n#13 0x556a901fe6df <unknown>\n#14 0x556a9025b308 <unknown>\n#15 0x556a9025b4e6 <unknown>\n#16 0x556a9026cb76 <unknown>\n#17 0x7ff3b4e9caa4 <unknown>\n#18 0x7ff3b4f29c3c <unknown>","statusTrace":"self = <test_registration_negative_email.TestTC object at 0x7ffb40179150>\n\n    def setup_method(self):\n>       self.browser = generate_preconfigured_browser()\n\nSprint_1/POM/Registration/test_registration_negative_email.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nSprint_1/POM/generate_preconfigured_browser.py:9: in generate_preconfigured_browser\n    browser = webdriver.Chrome(options=options)\n/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py:47: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py:69: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:257: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:356: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:447: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7ffb3fdf0ee0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x556a9026cb76 \\\\u003Cunknown>\\\\n#17 0x7ff3b4e9caa4 \\\\u003Cunknown>\\\\n#18 0x7ff3b4f29c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE       Stacktrace:\nE       #0 0x556a9026dc9a <unknown>\nE       #1 0x556a8fd136e0 <unknown>\nE       #2 0x556a8fd4e0b2 <unknown>\nE       #3 0x556a8fd4924f <unknown>\nE       #4 0x556a8fd998b6 <unknown>\nE       #5 0x556a8fd98f76 <unknown>\nE       #6 0x556a8fd8ac03 <unknown>\nE       #7 0x556a8fd5747b <unknown>\nE       #8 0x556a8fd580e1 <unknown>\nE       #9 0x556a9023244b <unknown>\nE       #10 0x556a9023637f <unknown>\nE       #11 0x556a90219f89 <unknown>\nE       #12 0x556a90236f18 <unknown>\nE       #13 0x556a901fe6df <unknown>\nE       #14 0x556a9025b308 <unknown>\nE       #15 0x556a9025b4e6 <unknown>\nE       #16 0x556a9026cb76 <unknown>\nE       #17 0x7ff3b4e9caa4 <unknown>\nE       #18 0x7ff3b4f29c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestTC","time":{"start":1750660239739,"stop":1750660239941,"duration":202},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x556a9026dc9a <unknown>\n#1 0x556a8fd136e0 <unknown>\n#2 0x556a8fd4e0b2 <unknown>\n#3 0x556a8fd4924f <unknown>\n#4 0x556a8fd998b6 <unknown>\n#5 0x556a8fd98f76 <unknown>\n#6 0x556a8fd8ac03 <unknown>\n#7 0x556a8fd5747b <unknown>\n#8 0x556a8fd580e1 <unknown>\n#9 0x556a9023244b <unknown>\n#10 0x556a9023637f <unknown>\n#11 0x556a90219f89 <unknown>\n#12 0x556a90236f18 <unknown>\n#13 0x556a901fe6df <unknown>\n#14 0x556a9025b308 <unknown>\n#15 0x556a9025b4e6 <unknown>\n#16 0x556a9026cb76 <unknown>\n#17 0x7ff3b4e9caa4 <unknown>\n#18 0x7ff3b4f29c3c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/python.py\", line 826, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/python.py\", line 722, in _call_with_optional_argument\n    func()\n  File \"/home/runner/work/webshop_projektmunka/webshop_projektmunka/Sprint_1/POM/Registration/test_registration_negative_email.py\", line 22, in setup_method\n    self.browser = generate_preconfigured_browser()\n  File \"/home/runner/work/webshop_projektmunka/webshop_projektmunka/Sprint_1/POM/generate_preconfigured_browser.py\", line 9, in generate_preconfigured_browser\n    browser = webdriver.Chrome(options=options)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 47, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 69, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 257, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 356, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"parentSuite","value":"Sprint_1.POM.Registration"},{"name":"suite","value":"test_registration_negative_email"},{"name":"subSuite","value":"TestTC"},{"name":"host","value":"fv-az2251-359"},{"name":"thread","value":"3263-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Sprint_1.POM.Registration.test_registration_negative_email"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"email","value":"'use r@teszt.hu'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"b4246fabad2a9c73.json","parameterValues":["'use r@teszt.hu'"]}